package java_Day_45;
import java.util.*;
public class EtsyAccount {
	private String email;
	private String firstName;
	private String password;
	
	//constructor 1
	public EtsyAccount(){
		email = "";
		firstName = "";
		password = "";
	}
	//constructor 2
	public EtsyAccount(String email, String firstName, String password) {
		setEmail(email);
		setFirstName(firstName);
		setPassword(password);
	}
	//constructor 3
	//params email & firstName , password is autogenerated and assigned
	public EtsyAccount(String email, String firstName) {
		setEmail(email);
		setFirstName(firstName);
		this.password = getRandomPassword();
	}
	
	//make private method getRandomPassword()
	private String getRandomPassword() {
		Random random = new Random();
		String letters = "abcdefghijklmnopqrstuvwxyz0123456789";
		String randomPassword = "";
		for(int i = 1; i <= 6; i++) { //will loop 6 times, the length of the password
			randomPassword += letters.charAt(random.nextInt(letters.length())); 
		}
		return randomPassword;
	}
	
	public String getEmail() {
		return email;
	}
	
	//if it contains @ somewhere in the middle, assign it, if not, print "Please enter valid email"
	public void setEmail(String email) {
		if(email.indexOf("@") > 0 && email.indexOf("@") != email.length()-1)  {
		this.email = email;
		}else {
			System.out.println("Please enter valid email");
		}
	}	
	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		if(isValidFirstName(firstName)) {
			this.firstName = firstName;
		}else{
			System.out.println("Your first name contians invalid characters");
		}
	}
	
	//firstName -> all letters, can have space in middle
	//invalid -> cannot contain numbers or other chars
	private boolean isValidFirstName(String firstName) {
	if(firstName.isEmpty()) {
		System.out.println("Cannot be blank");
		return false;
	}
	if(firstName.startsWith(" ") || firstName.endsWith(" ")) {
		return false;
	}
		for(int i = 0; i <= firstName.length()-1; i++) {
			char ch = firstName.charAt(i);
			if(!Character.isAlphabetic(ch) && ch != ' ') {  // if the char is not alphabetic and if the char is not a space then false
					return false;
		}
		}
		return true; 
	}
	
	public String getPassword() {
		return password;
	}
	
	public void setPassword(String password) {
		if(password.length() < 6) {
			System.out.println("Password must be more than 6 characters");
		}else {
		this.password = password;
		}
	}
	@Override
	public String toString() {
		return "EtsyAccount [email=" + email + ", firstName=" + firstName + ", password=" + password + "]";
	}
	
	
	
	
	
	
}
